package myproject.common

import java.util.{Currency, Locale}

object Geography {

  case class Address(street: Option[String], zip: Option[String], city: Option[String], country: Country)

  def getAllCountries = Countries.all

  def getCountry(code: String): Country = {
    Countries.all.find(c => c.iso2 == code || c.iso3 == code).getOrElse(throw ObjectNotFoundException(s"Country with country code `$code` was not found"))
  }

  case class Country(
      iso2: String,
      iso3: String,
      currency: Currency,
      name: String,
      locale: Locale,
      active: Boolean)

  object Country {
    def apply(iso2: String, iso3: String, currencyCode: String, name: String, languageTag: String, active: Boolean = false) = {
      new Country(iso2, iso3, Currency.getInstance(currencyCode), name, Locale.forLanguageTag(languageTag), active)
    }
  }

  private object Countries {
    val all = Vector(
      Country("AE","ARE","AED","United Arab Emirates","ar-AE"),
      Country("AF","AFG","AFN","Afghanistan","und-AF"),
      Country("AG","ATG","XCD","Antigua and Barbuda","und-AG"),
      Country("AI","AIA","XCD","Anguilla","und-AI"),
      Country("AL","ALB","ALL","Albania","sq-AL"),
      Country("AM","ARM","AMD","Armenia","und-AM"),
      Country("AN","ANT","ANG","Netherlands Antilles","und-AN"),
      Country("AO","AGO","AOA","Angola","und-AO"),
      Country("AR","ARG","ARS","Argentina","es-AR"),
      Country("AS","ASM","USD","American Samoa","und-AS"),
      Country("AT","AUT","EUR","Austria","de-AT"),
      Country("AU","AUS","AUD","Australia","en-AU"),
      Country("AW","ABW","AWG","Aruba","und-AW"),
      Country("AX","ALA","EUR","Åland Islands","und-AX"),
      Country("AZ","AZE","AZN","Azerbaijan","und-AZ"),
      Country("BA","BIH","BAM","Bosnia and Herzegovina","sr-BA-#Latn"),
      Country("BB","BRB","BBD","Barbados","und-BB"),
      Country("BD","BGD","BDT","Bangladesh","und-BD"),
      Country("BE","BEL","EUR","Belgium","fr-BE"),
      Country("BF","BFA","XOF","Burkina Faso","und-BF"),
      Country("BG","BGR","BGN","Bulgaria","bg-BG"),
      Country("BH","BHR","BHD","Bahrain","ar-BH"),
      Country("BI","BDI","BIF","Burundi","und-BI"),
      Country("BJ","BEN","XOF","Benin","und-BJ"),
      Country("BL","BLM","EUR","Saint Barthélemy","und-BL"),
      Country("BM","BMU","BMD","Bermuda","und-BM"),
      Country("BN","BRN","BND","Brunei","und-BN"),
      Country("BO","BOL","BOB","Bolivia","es-BO"),
      Country("BQ","BES","USD","Bonaire Sint Eustatius and Saba", "und-BQ"),
      Country("BR","BRA","BRL","Brazil","pt-BR"),
      Country("BS","BHS","BSD","Bahamas","und-BS"),
      Country("BT","BTN","BTN","Bhutan","und-BT"),
      Country("BV","BVT","NOK","Bouvet Island","und-BV"),
      Country("BW","BWA","BWP","Botswana","und-BW"),
      Country("BY","BLR","BYR","Belarus","be-BY"),
      Country("BZ","BLZ","BZD","Belize","und-BZ"),
      Country("CA","CAN","CAD","Canada","fr-CA"),
      Country("CC","CCK","AUD","Cocos Islands","und-CC"),
      Country("CD","COD","CDF","The Democratic Republic Of Congo","und-CD"),
      Country("CF","CAF","XAF","Central African Republic","und-CF"),
      Country("CG","COG","XAF","Congo","und-CG"),
      Country("CH","CHE","CHF","Switzerland","fr-CH"),
      Country("CI","CIV","XOF","Côte d'Ivoire","und-CI"),
      Country("CK","COK","NZD","Cook Islands","und-CK"),
      Country("CL","CHL","CLP","Chile","es-CL"),
      Country("CM","CMR","XAF","Cameroon","und-CM"),
      Country("CN","CHN","CNY","China","zh-CN"),
      Country("CO","COL","COP","Colombia","es-CO"),
      Country("CR","CRI","CRC","Costa Rica","es-CR"),
      Country("CU","CUB","CUP","Cuba","es-CU"),
      Country("CV","CPV","CVE","Cape Verde","und-CV"),
      Country("CW","CUW","ANG","Curaçao","und-CW"),
      Country("CX","CXR","AUD","Christmas Island","und-CX"),
      Country("CY","CYP","EUR","Cyprus","el-CY"),
      Country("CZ","CZE","CZK","Czech Republic","cs-CZ"),
      Country("DE","DEU","EUR","Germany","de-DE"),
      Country("DJ","DJI","DJF","Djibouti","und-DJ"),
      Country("DK","DNK","DKK","Denmark","da-DK"),
      Country("DM","DMA","XCD","Dominica","und-DM"),
      Country("DO","DOM","DOP","Dominican Republic","es-DO"),
      Country("DZ","DZA","DZD","Algeria","ar-DZ"),
      Country("EC","ECU","USD","Ecuador","es-EC"),
      Country("EE","EST","EUR","Estonia","et-EE"),
      Country("EG","EGY","EGP","Egypt","ar-EG"),
      Country("EH","ESH","MAD","Western Sahara","und-EH"),
      Country("ER","ERI","ERN","Eritrea","und-ER"),
      Country("ES","ESP","EUR","Spain","ca-ES"),
      Country("ET","ETH","ETB","Ethiopia","und-ET"),
      Country("FI","FIN","EUR","Finland","fi-FI"),
      Country("FJ","FJI","FJD","Fiji","und-FJ"),
      Country("FK","FLK","FKP","Falkland Islands","und-FK"),
      Country("FM","FSM","USD","Micronesia","und-FM"),
      Country("FO","FRO","DKK","Faroe Islands","und-FO"),
      Country("FR","FRA","EUR","France","fr-FR", active = true),
      Country("GA","GAB","XAF","Gabon","und-GA"),
      Country("GB","GBR","GBP","United Kingdom","en-GB", active = true),
      Country("GD","GRD","XCD","Grenada","und-GD"),
      Country("GE","GEO","GEL","Georgia","und-GE"),
      Country("GF","GUF","EUR","French Guiana","und-GF"),
      Country("GG","GGY","GBP","Guernsey","und-GG"),
      Country("GH","GHA","GHS","Ghana","und-GH"),
      Country("GI","GIB","GIP","Gibraltar","und-GI"),
      Country("GL","GRL","DKK","Greenland","und-GL"),
      Country("GM","GMB","GMD","Gambia","und-GM"),
      Country("GN","GIN","GNF","Guinea","und-GN"),
      Country("GP","GLP","EUR","Guadeloupe","und-GP"),
      Country("GQ","GNQ","XAF","Equatorial Guinea","und-GQ"),
      Country("GR","GRC","EUR","Greece","el-GR"),
      Country("GS","SGS","GBP","South Georgia And The South Sandwich Islands","und-GS"),
      Country("GT","GTM","GTQ","Guatemala","es-GT"),
      Country("GU","GUM","USD","Guam","und-GU"),
      Country("GW","GNB","XOF","Guinea-Bissau","und-GW"),
      Country("GY","GUY","GYD","Guyana","und-GY"),
      Country("HK","HKG","HKD","Hong Kong","zh-HK"),
      Country("HM","HMD","AUD","Heard Island And McDonald Islands","und-HM"),
      Country("HN","HND","HNL","Honduras","es-HN"),
      Country("HR","HRV","HRK","Croatia","hr-HR"),
      Country("HT","HTI","HTG","Haiti","und-HT"),
      Country("HU","HUN","HUF","Hungary","hu-HU"),
      Country("ID","IDN","IDR","Indonesia","in-ID"),
      Country("IE","IRL","EUR","Ireland","ga-IE"),
      Country("IL","ISR","ILS","Israel","iw-IL"),
      Country("IM","IMN","GBP","Isle Of Man","und-IM"),
      Country("IN","IND","INR","India","hi-IN"),
      Country("IO","IOT","USD","British Indian Ocean Territory","und-IO"),
      Country("IQ","IRQ","IQD","Iraq","ar-IQ"),
      Country("IR","IRN","IRR","Iran","und-IR"),
      Country("IS","ISL","ISK","Iceland","is-IS"),
      Country("IT","ITA","EUR","Italy","it-IT"),
      Country("JE","JEY","GBP","Jersey","und-JE"),
      Country("JM","JAM","JMD","Jamaica","und-JM"),
      Country("JO","JOR","JOD","Jordan","ar-JO"),
      Country("JP","JPN","JPY","Japan","ja-JP-JP-#u-ca-japanese"),
      Country("KE","KEN","KES","Kenya","und-KE"),
      Country("KG","KGZ","KGS","Kyrgyzstan","und-KG"),
      Country("KH","KHM","KHR","Cambodia","und-KH"),
      Country("KI","KIR","AUD","Kiribati","und-KI"),
      Country("KM","COM","KMF","Comoros","und-KM"),
      Country("KN","KNA","XCD","Saint Kitts And Nevis","und-KN"),
      Country("KP","PRK","KPW","North Korea","und-KP"),
      Country("KR","KOR","KRW","South Korea","ko-KR"),
      Country("KW","KWT","KWD","Kuwait","ar-KW"),
      Country("KY","CYM","KYD","Cayman Islands","und-KY"),
      Country("KZ","KAZ","KZT","Kazakhstan","und-KZ"),
      Country("LA","LAO","LAK","Laos","und-LA"),
      Country("LB","LBN","LBP","Lebanon","ar-LB"),
      Country("LC","LCA","XCD","Saint Lucia","und-LC"),
      Country("LI","LIE","CHF","Liechtenstein","und-LI"),
      Country("LK","LKA","LKR","Sri Lanka","und-LK"),
      Country("LR","LBR","LRD","Liberia","und-LR"),
      Country("LS","LSO","LSL","Lesotho","und-LS"),
      Country("LT","LTU","EUR","Lithuania","lt-LT"),
      Country("LU","LUX","EUR","Luxembourg","fr-LU"),
      Country("LV","LVA","EUR","Latvia","lv-LV"),
      Country("LY","LBY","LYD","Libya","ar-LY"),
      Country("MA","MAR","MAD","Morocco","ar-MA"),
      Country("MC","MCO","EUR","Monaco","und-MC"),
      Country("MD","MDA","MDL","Moldova","und-MD"),
      Country("ME","MNE","EUR","Montenegro","sr-ME"),
      Country("MF","MAF","EUR","Saint Martin","und-MF"),
      Country("MG","MDG","MGA","Madagascar","und-MG"),
      Country("MH","MHL","USD","Marshall Islands","und-MH"),
      Country("MK","MKD","MKD","Macedonia","mk-MK"),
      Country("ML","MLI","XOF","Mali","und-ML"),
      Country("MM","MMR","MMK","Myanmar","und-MM"),
      Country("MN","MNG","MNT","Mongolia","und-MN"),
      Country("MO","MAC","MOP","Macao","und-MO"),
      Country("MP","MNP","USD","Northern Mariana Islands","und-MP"),
      Country("MQ","MTQ","EUR","Martinique","und-MQ"),
      Country("MR","MRT","MRO","Mauritania","und-MR"),
      Country("MS","MSR","XCD","Montserrat","und-MS"),
      Country("MT","MLT","EUR","Malta","mt-MT"),
      Country("MU","MUS","MUR","Mauritius","und-MU"),
      Country("MV","MDV","MVR","Maldives","und-MV"),
      Country("MW","MWI","MWK","Malawi","und-MW"),
      Country("MX","MEX","MXN","Mexico","es-MX"),
      Country("MY","MYS","MYR","Malaysia","ms-MY"),
      Country("MZ","MOZ","MZN","Mozambique","und-MZ"),
      Country("NA","NAM","NAD","Namibia","und-NA"),
      Country("NC","NCL","XPF","New Caledonia","und-NC"),
      Country("NE","NER","XOF","Niger","und-NE"),
      Country("NF","NFK","AUD","Norfolk Island","und-NF"),
      Country("NG","NGA","NGN","Nigeria","und-NG"),
      Country("NI","NIC","NIO","Nicaragua","es-NI"),
      Country("NL","NLD","EUR","Netherlands","nl-NL"),
      Country("NO","NOR","NOK","Norway","nn-NO"),
      Country("NP","NPL","NPR","Nepal","und-NP"),
      Country("NR","NRU","AUD","Nauru","und-NR"),
      Country("NU","NIU","NZD","Niue","und-NU"),
      Country("NZ","NZL","NZD","New Zealand","en-NZ"),
      Country("OM","OMN","OMR","Oman","ar-OM"),
      Country("PA","PAN","PAB","Panama","es-PA"),
      Country("PE","PER","PEN","Peru","es-PE"),
      Country("PF","PYF","XPF","French Polynesia","und-PF"),
      Country("PG","PNG","PGK","Papua New Guinea","und-PG"),
      Country("PH","PHL","PHP","Philippines","en-PH"),
      Country("PK","PAK","PKR","Pakistan","und-PK"),
      Country("PL","POL","PLN","Poland","pl-PL"),
      Country("PM","SPM","EUR","Saint Pierre And Miquelon","und-PM"),
      Country("PN","PCN","NZD","Pitcairn","und-PN"),
      Country("PR","PRI","USD","Puerto Rico","es-PR"),
      Country("PS","PSE","ILS","Palestine","und-PS"),
      Country("PT","PRT","EUR","Portugal","pt-PT"),
      Country("PW","PLW","USD","Palau","und-PW"),
      Country("PY","PRY","PYG","Paraguay","es-PY"),
      Country("QA","QAT","QAR","Qatar","ar-QA"),
      Country("RE","REU","EUR","Reunion","und-RE"),
      Country("RO","ROU","RON","Romania","ro-RO"),
      Country("RS","SRB","RSD","Serbia","sr-RS"),
      Country("RU","RUS","RUB","Russia","ru-RU"),
      Country("RW","RWA","RWF","Rwanda","und-RW"),
      Country("SA","SAU","SAR","Saudi Arabia","ar-SA"),
      Country("SB","SLB","SBD","Solomon Islands","und-SB"),
      Country("SC","SYC","SCR","Seychelles","und-SC"),
      Country("SD","SDN","SDG","Sudan","ar-SD"),
      Country("SE","SWE","SEK","Sweden","sv-SE"),
      Country("SG","SGP","SGD","Singapore","en-SG"),
      Country("SH","SHN","SHP","Saint Helena","und-SH"),
      Country("SI","SVN","EUR","Slovenia","sl-SI"),
      Country("SJ","SJM","NOK","Svalbard And Jan Mayen","und-SJ"),
      Country("SK","SVK","EUR","Slovakia","sk-SK"),
      Country("SL","SLE","SLL","Sierra Leone","und-SL"),
      Country("SM","SMR","EUR","San Marino","und-SM"),
      Country("SN","SEN","XOF","Senegal","und-SN"),
      Country("SO","SOM","SOS","Somalia","und-SO"),
      Country("SR","SUR","SRD","Suriname","und-SR"),
      Country("SS","SSD","SSP","South Sudan","und-SS"),
      Country("ST","STP","STD","Sao Tome And Principe","und-ST"),
      Country("SV","SLV","SVC","El Salvador","es-SV"),
      Country("SX","SXM","ANG","Sint Maarten (Dutch part)", "und-SX"),
      Country("SY","SYR","SYP","Syria","ar-SY"),
      Country("SZ","SWZ","SZL","Swaziland","und-SZ"),
      Country("TC","TCA","USD","Turks And Caicos Islands","und-TC"),
      Country("TD","TCD","XAF","Chad","und-TD"),
      Country("TF","ATF","EUR","French Southern Territories","und-TF"),
      Country("TG","TGO","XOF","Togo","und-TG"),
      Country("TH","THA","THB","Thailand","th-TH"),
      Country("TJ","TJK","TJS","Tajikistan","und-TJ"),
      Country("TK","TKL","NZD","Tokelau","und-TK"),
      Country("TL","TLS","USD","Timor-Leste","und-TL"),
      Country("TM","TKM","TMT","Turkmenistan","und-TM"),
      Country("TN","TUN","TND","Tunisia","ar-TN"),
      Country("TO","TON","TOP","Tonga","und-TO"),
      Country("TR","TUR","TRY","Turkey","tr-TR"),
      Country("TT","TTO","TTD","Trinidad and Tobago","und-TT"),
      Country("TV","TUV","AUD","Tuvalu","und-TV"),
      Country("TW","TWN","TWD","Taiwan","zh-TW"),
      Country("TZ","TZA","TZS","Tanzania","und-TZ"),
      Country("UA","UKR","UAH","Ukraine","uk-UA"),
      Country("UG","UGA","UGX","Uganda","und-UG"),
      Country("UM","UMI","USD","United States Minor Outlying Islands","und-UM"),
      Country("US","USA","USD","United States","en-US", active = true),
      Country("UY","URY","UYU","Uruguay","es-UY"),
      Country("UZ","UZB","UZS","Uzbekistan","und-UZ"),
      Country("VA","VAT","EUR","Vatican","und-VA"),
      Country("VC","VCT","XCD","Saint Vincent And The Grenadines","und-VC"),
      Country("VE","VEN","VEF","Venezuela","es-VE"),
      Country("VG","VGB","USD","British Virgin Islands","und-VG"),
      Country("VI","VIR","USD","U.S. Virgin Islands","und-VI"),
      Country("VN","VNM","VND","Vietnam","vi-VN"),
      Country("VU","VUT","VUV","Vanuatu","und-VU"),
      Country("WF","WLF","XPF","Wallis And Futuna","und-WF"),
      Country("WS","WSM","WST","Samoa","und-WS"),
      Country("YE","YEM","YER","Yemen","ar-YE"),
      Country("YT","MYT","EUR","Mayotte","und-YT"),
      Country("ZA","ZAF","ZAR","South Africa","en-ZA"),
      Country("ZM","ZMB","ZMW","Zambia","und-ZM"),
      Country("ZW","ZWE","ZWL","Zimbabwe","und-ZW"))
  }
}

